services:
  opds-library:
    image: ghcr.io/samueleoraziodurante/opds-library:latest
    container_name: opds-library
    ports:
      - "3000:3000"
    volumes:
      - /path/to/your/books:/books
    restart: unless-stopped
